### ISSUE TITLE
first derivatives only?

### ISSUE THREAD

**Issue by stumarcus314** [BachiLi/had#2]
If I only need to construct the gradient of a function, is HAD a good choice? Does HAD automatically construct the information needed to construct second derivatives, even if they are not needed?

**Comment by BachiLi** [comment]
Hi, HAD can be used for gradient computation only, but it is not as efficient as some other AD libraries.  Currently HAD always propagates the second order information even if you only request first order ones.  I would recommend Adept ( http://www.met.reading.ac.uk/clouds/adept/ ) if you only need first-order derivatives.

**Comment by stumarcus576** [comment]
Does HAD use reverse-mode AD? Why do you recommend Adept over say Stan
Math? This paper about Stan Math (https://arxiv.org/pdf/1509.07164.pdf)
indicates that it is similar or even better than Adept.
